# -*- coding: utf-8 -*-
"""Unlabelled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsx1Lo4Nkp7fUBFAiQZ7rc8J3enptj8R
"""

# 2. Model Deployment –Deploy the best performing model on Unlabelled.csv and save
# its predictions to the same csv file.

import re, nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('omw-1.4')
nltk.download('wordnet')
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn import metrics
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
import joblib

# Reading dataset as dataframe
df = pd.read_csv("/content/drive/MyDrive/Unlabelled.csv")
pd.set_option('display.max_colwidth', None) # Setting this so we can see the full content of cells
pd.set_option('display.max_columns', None) # to make sure we can see all the columns in output window

df.shape

# Cleaning review
def cleaner(review):
    soup = BeautifulSoup(review, 'lxml') # removing HTML entities such as ‘&amp’,’&quot’,'&gt'; lxml is the html parser and shoulp be installed using 'pip install lxml'
    souped = soup.get_text()
    re1 = re.sub(r"(@|http://|https://|www|\\x)\S*", " ", souped) # substituting @mentions, urls, etc with whitespace
    re2 = re.sub("[^A-Za-z]+"," ", re1) # substituting any non-alphabetic character that repeats one or more times with whitespace

    """
    For more info on regular expressions visit -
    https://docs.python.org/3/howto/regex.html
    """

    tokens = nltk.word_tokenize(re2)
    lower_case = [t.lower() for t in tokens]

    stop_words = set(stopwords.words('english'))
    filtered_result = list(filter(lambda l: l not in stop_words, lower_case))

    wordnet_lemmatizer = WordNetLemmatizer()
    lemmas = [wordnet_lemmatizer.lemmatize(t,'v') for t in filtered_result]
    return lemmas

df['cleaned_Unlabelled'] = df.review.apply(cleaner)
df = df[df['cleaned_Unlabelled'].map(len) > 0] # removing rows with cleaned tweets of length 0

print("Printing top 20 rows of dataframe showing original and cleaned Unlabelled....")
print(df[['review','cleaned_Unlabelled']].head())
df.drop(['review'], axis=1, inplace=True)

df

df.shape

# Saving cleaned reviews to csv
df.to_csv('cleaned_data.csv', index=False)
df['cleaned_Unlabelled'] = [" ".join(row) for row in df['cleaned_Unlabelled'].values] # joining tokens to create strings. TfidfVectorizer does not accept tokens as input
data = df['cleaned_Unlabelled']
Y = df['sentiment'] # target column
tfidf = TfidfVectorizer(min_df=.0006, ngram_range=(1,3)) # min_df=.0006 means that each ngram (unigram, bigram, & trigram) must be present in at least 30 documents for it to be considered as a token (200000*.00015=30). This is a clever way of feature engineering
tfidf.fit(data) # learn vocabulary of entire data
data_tfidf = tfidf.transform(data) # creating tfidf values
pd.DataFrame(pd.Series(tfidf.get_feature_names_out())).to_csv('vocabulary.csv', header=False, index=False)
print("Shape of tfidf matrix: ", data_tfidf.shape)

from collections import Counter
Counter(Y)

import time
start_svc = time.time()
print("Implementing SVC.....")
# Implementing Support Vector Classifier
svc_clf = LinearSVC() # kernel = 'linear' and C = 1

# Running cross-validation
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1) # 10-fold cross-validation
scores=[]
iteration = 0
for train_index, test_index in kf.split(data_tfidf, Y):
    iteration += 1
    print("Iteration ", iteration)
    X_train, Y_train = data_tfidf[train_index], Y.iloc[train_index]
    X_test, Y_test = data_tfidf[test_index], Y.iloc[test_index]
    svc_clf.fit(X_train, Y_train) # Fitting SVC
    Y_pred = svc_clf.predict(X_test)
    score = metrics.accuracy_score(Y_test, Y_pred) # Calculating accuracy
    print("Cross-validation accuracy: ", score)
    scores.append(score) # appending cross-validation accuracy for each iteration
    end_svc = time.time()
time_taken = end_svc - start_svc
print('time taken is' ,time_taken )
svc_mean_accuracy = np.mean(scores)
print("Mean cross-validation accuracy: ", svc_mean_accuracy) # min_df=.0015 accuracy is 0.62, min_df=.0006 accuracy is 0.65, min_df=.0086 accuracy is 0.57

# Implementing Naive Bayes Classifier
nbc_clf = MultinomialNB()
import time
start_nbc = time.time()
# Running cross-validation
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1) # 10-fold cross-validation
scores=[]
iteration = 0
for train_index, test_index in kf.split(data_tfidf, Y):
    iteration += 1
    print("Iteration ", iteration)
    X_train, Y_train = data_tfidf[train_index], Y.iloc[train_index]
    X_test, Y_test = data_tfidf[test_index], Y.iloc[test_index]
    nbc_clf.fit(X_train, Y_train) # Fitting NBC
    Y_pred = nbc_clf.predict(X_test)
    score = metrics.accuracy_score(Y_test, Y_pred) # Calculating accuracy
    print("Cross-validation accuracy: ", score)
    scores.append(score) # appending cross-validation accuracy for each iteration
nbc_mean_accuracy = np.mean(scores)
print("Mean cross-validation accuracy: ", nbc_mean_accuracy) # min_df=.0015 accuracy is 0.62, min_df=.0006 accuracy is 0.65, min_df=.0086 accuracy is 0.56
end_nbc = time.time()
time_taken = end_nbc - start_nbc
print('time taken is' ,time_taken )

if svc_mean_accuracy > nbc_mean_accuracy:
  clf = LinearSVC().fit(data_tfidf, Y)
  joblib.dump(clf, 'svc.sav')
else:
  clf = MultinomialNB().fit(data_tfidf, Y)
  joblib.dump(clf, 'nbc.sav')